### ISSUE TITLE
Mis-type in -h output

### ISSUE THREAD

**Issue by kyrreaa** [EmBitz/EBlink#1]
One line starts with 't'.
Stray t from /t ?

**Comment by EmBitz** [comment]
Can't find it, perhaps already solved

**Comment by EmBitz** [comment]
Found it! 
In the Flash option help.

**Comment by AVI-crak** [comment]
Good afternoon.
The directory "https://git.embitz.org/Embitz/IDE" is empty.
I waited a long time for the night assembly. I guess I was left alone.
How much longer to wait?

**Comment by EmBitz** [comment]
Hi,

I'm switching to newer Mingw GCC versions and as soon as I have a buildable package. But I'm in the middle of a project so my time is limited.
