### ISSUE TITLE
scriptname and hostname at start

### ISSUE THREAD

**Issue by seniorandre** [EmBitz/EBlink#10]
Hello, Gerard,

First:
I continue to correct code for qt-creator .  Very not convenient that scriptname works only without extention.
- scriptname is accepted  as simple scriptname into script directory - ok
- scriptname is accepted  as absolute path + scriptname - ok
- scriptname is accepted  as relative path + scriptname -ok
but is not accepted with extention. Very difficult to do parse that with standart functions on crossplatform systems (convenient choose file and save it with path or w/o path).

Second:
Why is default host adress - 0.0.0.0, that address is not valid. But at the same time name "localhost" is not accepted? Host mame string is not need for connect to server, need only port. What a  function is hostname doing?

**Comment by EmBitz** [comment]
>  Second:
> Why is default host adress - 0.0.0.0, that address is not valid. But at the same time name "localhost" is not accepted? Host mame string is not need for connect to server, need only port. What a function is hostname doing?

Sure it is, it means "bind to any interface".
https://stackoverflow.com/questions/20778771/what-is-the-difference-between-0-0-0-0-127-0-0-1-and-localhost

Extensions: I will look into that one.

**Comment by EmBitz** [comment]
User extensions are allowed in the next update.
Thanks!

**Comment by seniorandre** [comment]
Thanks!

**Comment by EmBitz** [comment]
I also added to possibility to add several scripts (e.g. user or platform specific reset strategies).

Like:
-D stm32-auto,myReset.scr 

for the stm32-auto the .script will be used because no extension
for the myReset.scr this file name will be used because it has an extension

**Comment by seniorandre** [comment]
In other words. the main script is always without an extension and additional scripts always with the expansion?

**Comment by EmBitz** [comment]
No, if you give the main script an extension, it will uses that one.

Every script filename is checked if there is an extension, otherwise it will use .script. It needs an extension.

**Comment by seniorandre** [comment]
Ok I understood you. Ican use scriptname with extension and w/o extension.

**Comment by EmBitz** [comment]
Yip, and w/o extension will result in default <file>.script
