### ISSUE TITLE
Semihosting

### ISSUE THREAD

**Issue by Miinik** [EmBitz/EBlink#19]
EBLink does not support Semihosting? Why?

![Semihosting](https://user-images.githubusercontent.com/58473436/77649627-d6dd3e80-6f72-11ea-9b8f-9d45371aa0c5.png)

**Comment by EmBitz** [comment]
No time yet, I will start with it today. 
I personally don't use it anymore so I didn't missed it.

**Comment by EmBitz** [comment]
[eblink_2_1.zip](https://github.com/EmBitz/EBlink/files/4415673/eblink_2_1.zip)

I did a quick test and it worked here but perhaps you can test it a bit more.
Thanks

**Comment by EmBitz** [comment]
Sorry, found a small hick up

**Comment by Miinik** [comment]
Works great.
Thanks for update.
