### ISSUE TITLE
source code

### ISSUE THREAD

**Issue by stappersg** [EmBitz/EBlink#22]
Where is the source code?

**Comment by EmBitz** [comment]
Hoi Geert, op mijn server.

**Comment by stappersg** [comment]
> Any problems with the STM32L072 support?

Yes, but not big enough to bail out to binary blobs    :-)

**Comment by EmBitz** [comment]
All the device related stuff is in EBlink done with c-like scripting so need for binary or even source code. 
It's all about the script.

**Comment by stappersg** [comment]
On Mon, Jul 20, 2020 at 12:03:57AM -0700, EmBitz wrote:
> All the device related stuff is in EBlink done with c-like scripting so need for binary or even source code. 
> It's all about the script. 

And where to find the script and how the recognize it?

**Comment by EmBitz** [comment]
In the /scripts folder of this repro perhaps?

I have the feeling that you are a bit lost here. Any experiences with bare metal development?

**Comment by stappersg** [comment]
FWIW there is https://github.com/EmBitz/EBlink/blob/master/scripts/stmicro/stm32l0x.script

**Comment by EmBitz** [comment]
If you need a GDB debugger or cli flash tool, just follow the readme.md and everything falls in place. It's so awful simple.

If you need source code to hack then I would suggest OpenOCD as starting point.

**Comment by Miinik** [comment]
Didn't find descriptions of functions used in scripts. One has to guess what each of the functions is for by studying scripts. It would be great if there was a list of all the functions used in the scripts and their description.
