### ISSUE TITLE
Include directories missing

### ISSUE THREAD

**Issue by TobiasWallner** [EmBitz/EBlink#29]
Hi.
First of all I really like yor project :) 

I installed everything, made a STM32F4 project, rebuild the workspace and got a lot of -Wimlicit-function errors. 
I found out that the define directive for assert_param which is found in the stm32f4xx_conf.h is never included in any file found in the SPL\src folder.

sincerely,
Tobias

**Comment by EmBitz** [comment]
Hi, thanks.
This is about Embitz I think? 
Those integrated SPL's are rather old, I think that Miink has some new ones for EB. You can find Miink at the embitz forum
https://www.embitz.org/forum

**Comment by TobiasWallner** [comment]
oh thanks :)
