### ISSUE TITLE
Crash EBlink 3.8.0.50 if ST-Link not connected

### ISSUE THREAD

**Issue by Miinik** [EmBitz/EBlink#30]
When ST-Link is not connected to the computer and EBlink is launched with command line 
`-I stlink,swd -S stm32-auto -a -F file=Firmware.hex,verify,run`
EBlink crashes.

**Comment by EmBitz** [comment]
If I try it in a cmd shell or on linux I get a message (with box on windows) with "No interface found" and EBlink quits.
I can't reproduce it.

**Comment by EmBitz** [comment]
During testing and checking your issue I noticed that the cursor was not set back after the error message. 
Changed this in the 3.8[52]

**Comment by Miinik** [comment]
3.8.0.53 no problem.
3.8.0.50 - crashs after reports **No interface found**
