### ISSUE TITLE
High CPU power use GDB

### ISSUE THREAD

**Issue by Miinik** [EmBitz/EBlink#38]
Current version EBlink 4.3 uses a lot of processor time (fully one core). 
For example for 4 core processor, use will be 25%.
In version 3.9 there is no this problem.

**Comment by EmBitz** [comment]
This is after the introduction of a service manager.

EBlink can now have multiple services at the same time such as two GDB servers (multi-core) or ITM etc.
I could bring this down but probably this will affect the response time of EBlink.
