### ISSUE TITLE
source code

### ISSUE THREAD

**Issue by bm16ton** [EmBitz/EBlink#40]
Is this closed source? If so any chance of a mention IE HUGE WARNING in the readme? Was super excited too. Shame

**Comment by EmBitz** [comment]
I offered 2 years ago in the stlink-org repro to replace that with this. Response, zero! Nada!
stlink-org went on with their source pool and I decided to make this freeware.

Why is it on git, because of scripts. 

I will transfer the packages etc to EmBitz site and keep the scripts here.
