### ISSUE TITLE
How to use EBlink in EmBitz 1.11

### ISSUE THREAD

**Issue by Tiilk** [EmBitz/EBlink#6]
Hello!
How to use EBlink in EmBitz 1.11?
I searched, but did not find how to do it.
Thanks.

**Comment by EmBitz** [comment]
![Embitz 1.11 interfrace settings](https://www.sysdes.nl/github/eb11EBlink1.png)  

![mbitz 1.11 interfrace settings](https://www.sysdes.nl/github/eb11EBlink2.png)

**Comment by EmBitz** [comment]
And put in the "after connect":

`load`

in order to load (flash) the program.

**Comment by Miinik** [comment]
I added EBlink to list of debugger interfaces for EmBitz 1.11.

![1](https://user-images.githubusercontent.com/58473436/70559421-4596b780-1b8f-11ea-8805-e96df99af757.png)

To add, you need to extract this archive https://www.dropbox.com/s/4xzul9eagrpakju/EBlink_Interface_for_EmBitz_1_11.zip
to a folder 

> ${EMBITZ}\share\EmBitz\debuggers\Interfaces\  

EBlink must be installed in the folder

> ${EMBITZ}\share\EBlink

**${EMBITZ}** this is the folder in which EmBitz is installed. Usually this 

> C:\Program Files (x86)\EmBitz\1.11\

**Comment by EmBitz** [comment]
Great, thanks!

**Comment by Miinik** [comment]
Unfortunately I do not have much free time...

**Comment by EmBitz** [comment]
Thanks, pity.

**Comment by Miinik** [comment]
Updated debug interface for [EBlink 2.0](https://github.com/EmBitz/EBlink/releases/tag/2.0)
https://www.dropbox.com/s/ylyhi1b826b5fq7/EBlink_2.0_Interface_for_EmBitz_1_11.zip
