### ISSUE TITLE
-exec-interrupt -> SIGTRAP

### ISSUE THREAD

**Issue by seniorandre** [EmBitz/EBlink#8]
Hi Gerard,

And me again... with QtCreator IDE
When I send to EBlink signal -exec-interrupt, then is returned a response SIGTRAP.
and Creator show dialog message SIGTRAP.
Another debuggers return SIGINT response.
Can you change it?

Andrey.

![2019-12-02 20_19_29-main c @ stm32template  1890M  - Qt Creator](https://user-images.githubusercontent.com/6779506/69981013-77ca6880-1542-11ea-853c-cd68c8b575b5.jpg)
![2019-12-02 20_19_58-main c @ stm32template  1890M  - Qt Creator](https://user-images.githubusercontent.com/6779506/69981019-7bf68600-1542-11ea-84da-2ba30837b0ab.jpg)

**Comment by EmBitz** [comment]
Are you sure? It is now sending a "S05" on halt but I can't find any spec which stipulates that it should be different. What should it be according you?

**Comment by EmBitz** [comment]
Why is QT Creator  showing a message box when it hits a breakpoint, is that normal behaviour?  I would expect that it just update the UI of the IDE with the new status. At least that's how I did it when I build Embitz.

**Comment by seniorandre** [comment]
-exect-interrupt is sent when you press interrupt for exit from infinit while(1) for example, without breakpoint.
Open OCD returns on that situation SIGINT and Creator is stoped on any line into while without the dialog.

https://en.wikipedia.org/wiki/Signal_(IPC)#SIGINT

![2019-12-02 21_36_55-main c @ stm32template  1890M  - Qt Creator](https://user-images.githubusercontent.com/6779506/69985354-10191b00-154c-11ea-8393-34d8e238df86.jpg)

**Comment by EmBitz** [comment]
Yes, I just see that OpenOCD returns a S02 but stlink is just returning S05.  If I recall correctly, J-link server is also returning S05. From an IDE perspective, it is not important if it's S05 or S02 because the reason is in the stop frame.  Why should an IDE do differently between a stop with S02 or S05?

I will look into this, if I don't need to change this then I prefer to keep it this way. Using S05 is just straight forward, on status change to halt->throw S05. Otehrwise I have to keep track what the reason is, and what if we have a race condition ( -exec-interrupt on breakpoint trap) ?

But if this should be S02 to make it more compatible then I will do it for sure.

**Comment by EmBitz** [comment]
What I could do is using the NVIC  (dfsr) debug fault status register and if the HALTED flag is the only one set, return S02. I think that that will do the trick. If any of the other flags are also set, I will return S05. 

http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.ddi0337e/Cihcbadd.html

**Comment by seniorandre** [comment]
Into code I have found setting. :)

![2019-12-02 22_04_56-gdbengine cpp (gdb @ debugger)  62785M  - Qt Creator](https://user-images.githubusercontent.com/6779506/69987188-fd084a00-154f-11ea-8674-eab5a9191675.jpg)
![2019-12-02 22_04_30-Options - Qt Creator](https://user-images.githubusercontent.com/6779506/69987204-0396c180-1550-11ea-8776-fa37b8bd671a.jpg)

**Comment by seniorandre** [comment]
> . If any of the other flags are also set, I will return S05.

It will be right .

**Comment by EmBitz** [comment]
Yip, that's make sense. That stop code shouldn't be that important for the IDE, the stop frame should be parsed anyway.

I keep this in mind and if others are complaining I will change this. I just did some test how that DFSR register is handling the stop reasons. I think I could do something meaningful with it if necessary.

**Comment by EmBitz** [comment]
Hi,

Could you try this version?  I'm parsing the stop reason from the core. 

[eblink.zip](https://github.com/EmBitz/EBlink/files/3913087/eblink.zip)

**Comment by seniorandre** [comment]
That version do not works right. I have spontaneous interrupt on start.
![2019-12-02 23_17_51-core_cm3 c (R___PROJECTS_54_Creator_cMake_Spl_CMSIS_CM3_CoreSupport @ stm32templ](https://user-images.githubusercontent.com/6779506/69992295-65f4bf80-155a-11ea-9fbe-f68fa40bc56f.jpg)

**Comment by EmBitz** [comment]
Thanks.
