### ISSUE TITLE
Interrupt call failed: svc 0x0

### ISSUE THREAD

**Issue by AVI-crak** [EmBitz/EBlink#9]
Hello again.
My code stops at the command "svc 0x0", the LR register shows the transition to the interrupt mode 0xFFFFFFED, while the PC register is outside the range 0xFFFFFFFE. Interrupts are identified and recorded. For them there is program code with real addresses from the interrupt table. If you manually change the PC to the interrupt address, then the code is executed and correctly exits to the main program.

Extras: very long loading of a data image, tens of minutes. The server is trying to allocate memory for the external memory section, it is large, but it is marked for reading.
![Temp33](https://user-images.githubusercontent.com/35156298/70087439-872edc00-163e-11ea-9c03-c91a21b7a585.jpg)

**Comment by EmBitz** [comment]
And why should this be a eblink problem? 
I did a OS project with task switching without  problems. Don't think this is eblink related.

**Comment by EmBitz** [comment]
AVI, there was a fault in the EBlink which could explain your behaviour. 
I will see if I can update it tomorrow, Sorry!
